### ISSUE TITLE
Cancel download aborts with Assertion

### ISSUE THREAD

**Issue by bomilkar** [XCSoar/XCSoar#1052]
XCSoar versions having and not having the problem
-------------------------------------------------

The current master has the problem on PC and UNIX but not on ANDROID

The problem does not exist in unreleased versions of 7.24 prior to March 12, 2022. For instance git 680168f0cd

Expected behavior
-----------------

The Cancel button on the Download page, which appears when a mapfile, airspace file, waypoint file, etc is downloaded, should cancel the current download and should not abort with an assertion. 

Actual behavior
---------------

When downloading a file (map, airspace, waypoint, ...) either through Config->System-Sitefiles or through the File Manager, a "Cancel" button appears in the top right corner of the progress screen. Hitting that "Cancel" button immediately leads to:

```
xcsoar: src/net/http/DownloadManager.cpp:260: void DownloadManagerThread::Start(): Assertion `current_size == -1' failed.

Thread 1 "xcsoar" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50

```
(the lines above are from gdb. On PC or plain UNIX it looks a bit different but to the same effect.)

Steps to reproduce the behavior
-------------------------------

On PC or UNIX download a map file, for instance ALPS_HighRes.xcm. (Don't try it on ANDROID because the issue doesn't exist there.)
You should see the progress screen of the download.
Press the Cancel button in the top right corner.
XCSoar will abort as the assertion fails.

Do you have any idea what may have caused this?
-----------------------------------------------

Do you have an idea how to solve the issue?
-------------------------------------------

**Comment by bomilkar** [comment]
I found this issue when was trying to narrow down a different problem: On Raspberry Pi4 and Cubie2 (but not on UNIX or PC) I saw file downloads crashing AFTER the file download had finished but before the download progress page ended.
I'm speculating: these 2 issues might be related, so looking at the 2nd issue may help fixing the first.

In these cases XCSoar aborts with segmentation fault and a core dump. The message in gdb is:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0025379c in DownloadManagerThread::OnCompletion (this=0x1021e60, error=...)
    at src/net/http/DownloadManager.cpp:288
288           listener->OnDownloadComplete(path_relative);
[Current thread is 1 (Thread 0xad9fcfc0 (LWP 6304))]
(gdb) backtrace
#0  0x0025379c in DownloadManagerThread::OnCompletion(std::__exception_ptr::exception_ptr)
    (this=0x1021e60, error=...) at src/net/http/DownloadManager.cpp:288
#1  0x00253aa8 in BindMethodDetail::WrapperGenerator<void (DownloadManagerThread::*)(std::__exception_ptr::exception_ptr) noexcept, &DownloadManagerThread::OnCompletion>::Invoke(void*, std::__exception_ptr::exception_ptr) (_instance=<optimized out>, args#0=...)
    at ./src/util/BindMethod.hxx:130
#2  0x00256c7c in BoundMethod<void (std::__exception_ptr::exception_ptr) noexcept>::operator()(std::__exception_ptr::exception_ptr) const (args#0=..., this=0x1021e7c)
    at ./src/util/BindMethod.hxx:78
#3  Co::InjectTask::OnCompletion(std::__exception_ptr::exception_ptr)
    (this=0x1021e64, error=...) at src/co/InjectTask.cxx:91
.
.

```
Looking at it with "SANITIZE=y" reveals a bit more:

```

        __for_range = Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer':
empty std::__debug::list
        __for_begin = <error reading variable: Cannot access memory at address 0xd1>
        __for_end = <error reading variable: Cannot access memory at address 0x2e>
        __PRETTY_FUNCTION__ = "void DownloadManagerThread::OnCompletion(std::__exception_ptr::exception_ptr)"
        path_relative = {static SENTINEL = 0 '\000', value = {static SENTINEL = <optimized out>, value = 0x1922660 "src/Math/XYDataStore.cpp"}}
#4  __gnu_debug::_Safe_iterator<std::__cxx1998::_List_iterator<Net::DownloadListener*>, std::__debug::list<Net::DownloadListener*, std::allocator<Net::DownloadListener*> >, std::bidirectional_iterator_tag>::operator++() (this=<optimized out>) at /usr/include/c++/10/debug/safe_iterator.h:579
        listener = <optimized out>
        __for_range = Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer':
empty std::__debug::list
        __for_begin = <error reading variable: Cannot access memory at address 0xd1>
        __for_end = <error reading variable: Cannot access memory at address 0x2e>
        __PRETTY_FUNCTION__ = "void DownloadManagerThread::OnCompletion(std::__exception_ptr::exception_ptr)"
        path_relative = {static SENTINEL = 0 '\000', value = {static SENTINEL = <optimized out>, value = 0x1922660 "src/Math/XYDataStore.cpp"}}


```
