### ISSUE TITLE
ANDROID target won't build as of 0132481

### ISSUE THREAD

**Issue by styblope** [XCSoar/XCSoar#1231]
Won't build ANDROID target as of 0132481d55fc637d99d57e9fa5481bd0ab5a46ff. Tested using Docker builder.

```
make clean
make TARGET=ANDROIDAARCH64 DEBUG=n USE_CCACHE=y
```

Fails with error:
```
CMake Error at CMakeLists.txt:176 (message):
  sqlite3 binary not found!


-- Found Sqlite3: /home/petr/Projects/XCSoar/output/ANDROID/arm64-v8a/lib/aarch64-linux-android/lib/libsqlite3.a
-- Sqlite3 version: 3.34.1
CMake Warning at CMakeLists.txt:206 (message):
  TIFF support is not enabled and will result in the inability to read some
  grids


-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Performing Test HAVE_PTHREAD_MUTEX_RECURSIVE_DEFN
-- Performing Test HAVE_PTHREAD_MUTEX_RECURSIVE_DEFN - Success
-- Testing disabled
-- Configuring proj library:
-- ENABLE_IPO                     = OFF
-- PROJ_CORE_TARGET_OUTPUT_NAME   = proj
-- BUILD_SHARED_LIBS              = OFF
-- PROJ_LIBRARIES                 = proj
-- PROJ: Configured 'dist' target
-- Configuring incomplete, errors occurred!
See also "/home/petr/Projects/XCSoar/output/ANDROID/arm64-v8a/lib/build/proj-9.1.0/CMakeFiles/CMakeOutput.log".
See also "/home/petr/Projects/XCSoar/output/ANDROID/arm64-v8a/lib/build/proj-9.1.0/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/home/petr/Projects/XCSoar/./build/thirdparty.py", line 202, in <module>
    x.build(toolchain)
  File "/home/petr/Projects/XCSoar/build/python/build/project.py", line 80, in build
    self._build(toolchain)
  File "/home/petr/Projects/XCSoar/build/python/build/cmake.py", line 122, in _build
    build = self.configure(toolchain)
  File "/home/petr/Projects/XCSoar/build/python/build/cmake.py", line 118, in configure
    configure(toolchain, src, build, configure_args, self.env)
  File "/home/petr/Projects/XCSoar/build/python/build/cmake.py", line 100, in configure
    subprocess.check_call(configure, env=env, cwd=build)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/petr/Projects/XCSoar/output/src/proj-9.1.0', '-DCMAKE_TOOLCHAIN_FILE=/home/petr/Projects/XCSoar/output/ANDROID/arm64-v8a/lib/build/proj-9.1.0/cmake_toolchain_file', '-DCMAKE_INSTALL_PREFIX=/home/petr/Projects/XCSoar/output/ANDROID/arm64-v8a/lib/aarch64-linux-android', '-DCMAKE_BUILD_TYPE=release', '-GNinja', '-DBUILD_TESTING=OFF', '-DENABLE_TIFF=OFF', '-DENABLE_CURL=OFF', '-DBUILD_CCT=OFF', '-DBUILD_CS2CS=OFF', '-DBUILD_GEOD=OFF', '-DBUILD_GIE=OFF', '-DBUILD_PROJ=OFF', '-DBUILD_PROJINFO=OFF', '-DBUILD_PROJSYNC=OFF', '-DBUILD_SHARED_LIBS=OFF', '-DUSE_THREAD=OFF']' returned non-zero exit status 1.
make: *** [build/thirdparty.mk:41: output/ANDROID/arm64-v8a/lib/stamp] Error 1
rm output/ANDROID/arm64-v8a/opt/src/Device/Driver/../dirstamp output/host/tools/GenerateSineTables/../dirstampmake: unlink: output/host/tools/GenerateSineTables/../dirstamp: Not a directory
 output/host/tools/GenerateSineTables.o
```

**Comment by lordfolken** [comment]
We don't install sqlite3 in https://github.com/XCSoar/XCSoar/blob/master/ide/provisioning/install-debian-packages.sh therefore its not available in the container. Hooray for clean build environments.

**Comment by styblope** [comment]
Patching out the Sqlite CLI dependency check from Proj seems to me as a better way than bringing back the dependency via platform-misaligned OS package.

```
Index: proj-9.1.0/CMakeLists.txt
===================================================================
--- proj-9.1.0.orig/CMakeLists.txt
+++ proj-9.1.0/CMakeLists.txt
@@ -171,11 +171,6 @@
 # Check for sqlite3
 ################################################################################
 
-find_program(EXE_SQLITE3 sqlite3)
-if(NOT EXE_SQLITE3)
-  message(SEND_ERROR "sqlite3 binary not found!")
-endif()
-
 find_package(Sqlite3 REQUIRED)
 if(NOT SQLITE3_FOUND)
   message(SEND_ERROR "sqlite3 dependency not found!")
```

**Comment by MaxKellermann** [comment]
What do you mean by "platform-misaligned OS package"?
Is sqlite needed or not?

**Comment by styblope** [comment]
No, not used. Proj only uses it for [data](https://github.com/OSGeo/PROJ/tree/9.1/data) build, which we already exclude via `lib/proj/patches/no_data` patch.

**Comment by MaxKellermann** [comment]
OK then, agree to patch the check out
